### ISSUE TITLE
undefined local variable or method `current_user'

### ISSUE THREAD

**Issue by dja** [lml/fine_print#17]
On a fresh install, first time setting up fine_print, I'm seeing this issue. Seems like it has to do with having current_user in the lambda of the initializer?

```
undefined local variable or method `current_user' for #<FinePrint::HomeController:0x0000011c04f160>
```

**Comment by danieljacobarcher** [comment]
Hey @Dantemss have you encountered this at all?

**Comment by Dantemss** [comment]
Hello. Please define your `current_user` method in ActionController::Base. Thanks.
